/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Compass

#ifndef _COMPASS_UI_H
#define _COMPASS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_CompassCorrectScreen.h"
#include "screens/ui_CompassScreen.h"
#include "screens/ui_CompassTipScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS

extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_correct_screen_png);    // assets/correct_screen.png
LV_IMG_DECLARE(ui_img_compass_base_png);    // assets/compass_base.png
LV_IMG_DECLARE(ui_img_compass_pointer_png);    // assets/compass_pointer.png

// UI INIT
void compass_ui_init(bool is_initialized);
void compass_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
