/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Temp

#include "../ui.h"

lv_obj_t *ui_TemperatureTipScreen = NULL;
lv_obj_t *ui_TemperatureTipText = NULL;
// event functions

// build functions

void ui_TemperatureTipScreen_screen_init(void)
{
    ui_TemperatureTipScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TemperatureTipScreen, LV_OBJ_FLAG_SCROLLABLE);

    ui_TemperatureTipText = lv_label_create(ui_TemperatureTipScreen);
    lv_obj_set_width(ui_TemperatureTipText, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TemperatureTipText, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_TemperatureTipText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureTipText, "BME690 sub-board not detected.\nPower off and insert sub-board.\nDo NOT hot-plug.");
    lv_label_set_long_mode(ui_TemperatureTipText, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(ui_TemperatureTipText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TemperatureTipText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_TemperatureTipScreen_screen_destroy(void)
{
    if (ui_TemperatureTipScreen) {
        lv_obj_del(ui_TemperatureTipScreen);
    }

    ui_TemperatureTipScreen = NULL;
    ui_TemperatureTipText = NULL;

}
