/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Temp

#include "../ui.h"

lv_obj_t *ui_TemperatureScreen = NULL;
lv_obj_t *ui_Temperature = NULL;
lv_obj_t *ui_TemperatureLabel = NULL;
lv_obj_t *ui_TemperatureNumber = NULL;
lv_obj_t *ui_TemperatureSignal = NULL;
lv_obj_t *ui_Thermometer = NULL;
lv_obj_t *ui_Fire = NULL;
lv_obj_t *ui_Humidity = NULL;
lv_obj_t *ui_HumidityLabel = NULL;
lv_obj_t *ui_Water = NULL;
lv_obj_t *ui_HumidityNumber = NULL;
lv_obj_t *ui_HumidityUnit = NULL;
lv_obj_t *ui_HumidityEvaluation = NULL;
lv_obj_t *ui_Pressure = NULL;
lv_obj_t *ui_PressureLabel = NULL;
lv_obj_t *ui_PressureImage = NULL;
lv_obj_t *ui_PressureText = NULL;
lv_obj_t *ui_PressureUnit = NULL;
lv_obj_t *ui_PressureTrend = NULL;
lv_obj_t *ui_AirQuality = NULL;
lv_obj_t *ui_AirQualityLabel = NULL;
lv_obj_t *ui_Leaf = NULL;
lv_obj_t *ui_AirQualityCO2 = NULL;
lv_obj_t *ui_AirQualityNumber = NULL;
lv_obj_t *ui_AirQualityLevel = NULL;
lv_obj_t *ui_AirQualitySignal = NULL;
// event functions

// build functions

void ui_TemperatureScreen_screen_init(void)
{
    ui_TemperatureScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TemperatureScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_TemperatureScreen, lv_color_hex(0xF6EFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TemperatureScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_obj_create(ui_TemperatureScreen);
    lv_obj_remove_style_all(ui_Temperature);
    lv_obj_set_width(ui_Temperature, lv_pct(40));
    lv_obj_set_height(ui_Temperature, lv_pct(40));
    lv_obj_set_x(ui_Temperature, lv_pct(-23));
    lv_obj_set_y(ui_Temperature, lv_pct(-25));
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Temperature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_Temperature, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Temperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureLabel = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_TemperatureLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TemperatureLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_TemperatureLabel, 10);
    lv_obj_set_y(ui_TemperatureLabel, 5);
    lv_label_set_text(ui_TemperatureLabel, "Temperature");
    lv_obj_set_style_text_font(ui_TemperatureLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureNumber = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_TemperatureNumber, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TemperatureNumber, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_TemperatureNumber, 3);
    lv_obj_set_y(ui_TemperatureNumber, 5);
    lv_obj_set_align(ui_TemperatureNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureNumber, "25.00");
    lv_obj_set_style_text_font(ui_TemperatureNumber, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureSignal = lv_label_create(ui_Temperature);
    lv_obj_set_width(ui_TemperatureSignal, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TemperatureSignal, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_TemperatureSignal, 40);
    lv_obj_set_y(ui_TemperatureSignal, 0);
    lv_obj_set_align(ui_TemperatureSignal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TemperatureSignal, "°C");

    ui_Thermometer = lv_image_create(ui_Temperature);
    lv_image_set_src(ui_Thermometer, &ui_img_temp_png);
    lv_obj_set_width(ui_Thermometer, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Thermometer, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Thermometer, -40);
    lv_obj_set_y(ui_Thermometer, 5);
    lv_obj_set_align(ui_Thermometer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thermometer, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Thermometer, LV_OBJ_FLAG_SCROLLABLE);

    ui_Fire = lv_image_create(ui_Temperature);
    lv_image_set_src(ui_Fire, &ui_img_fire_png);
    lv_obj_set_width(ui_Fire, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Fire, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Fire, 40);
    lv_obj_set_y(ui_Fire, 30);
    lv_obj_set_align(ui_Fire, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fire, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Fire, LV_OBJ_FLAG_SCROLLABLE);

    ui_Humidity = lv_obj_create(ui_TemperatureScreen);
    lv_obj_remove_style_all(ui_Humidity);
    lv_obj_set_width(ui_Humidity, lv_pct(40));
    lv_obj_set_height(ui_Humidity, lv_pct(40));
    lv_obj_set_x(ui_Humidity, lv_pct(23));
    lv_obj_set_y(ui_Humidity, lv_pct(-25));
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Humidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_Humidity, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Humidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityLabel = lv_label_create(ui_Humidity);
    lv_obj_set_width(ui_HumidityLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_HumidityLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_HumidityLabel, 10);
    lv_obj_set_y(ui_HumidityLabel, 5);
    lv_label_set_text(ui_HumidityLabel, "Humidity");
    lv_obj_set_style_text_font(ui_HumidityLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityNumber = lv_label_create(ui_Humidity);
    lv_obj_set_width(ui_HumidityNumber, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_HumidityNumber, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_HumidityNumber, 0);
    lv_obj_set_y(ui_HumidityNumber, 0);
    lv_obj_set_align(ui_HumidityNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityNumber, "50.00");
    lv_obj_set_style_text_font(ui_HumidityNumber, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityUnit = lv_label_create(ui_Humidity);
    lv_obj_set_width(ui_HumidityUnit, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_HumidityUnit, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_HumidityUnit, 37);
    lv_obj_set_y(ui_HumidityUnit, -7);
    lv_obj_set_align(ui_HumidityUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityUnit, "%");
    lv_obj_set_style_text_font(ui_HumidityUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumidityUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityEvaluation = lv_label_create(ui_Humidity);
    lv_obj_set_width(ui_HumidityEvaluation, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_HumidityEvaluation, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_HumidityEvaluation, 0);
    lv_obj_set_y(ui_HumidityEvaluation, 24);
    lv_obj_set_align(ui_HumidityEvaluation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityEvaluation, "^_^");
    lv_obj_set_style_text_font(ui_HumidityEvaluation, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_HumidityEvaluation, lv_color_hex(0x4CAF50), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Water = lv_image_create(ui_Humidity);
    lv_image_set_src(ui_Water, &ui_img_water_png);
    lv_obj_set_width(ui_Water, 32);  // Keep container size larger
    lv_obj_set_height(ui_Water, 32);  // Keep container size larger
    lv_image_set_scale(ui_Water, (int)(0.65f * LV_SCALE_NONE));  // Scale image content to 65%
    lv_obj_set_x(ui_Water, 40);
    lv_obj_set_y(ui_Water, 30);
    lv_obj_set_align(ui_Water, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Water, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Water, LV_OBJ_FLAG_SCROLLABLE);

    ui_Pressure = lv_obj_create(ui_TemperatureScreen);
    lv_obj_remove_style_all(ui_Pressure);
    lv_obj_set_width(ui_Pressure, lv_pct(40));
    lv_obj_set_height(ui_Pressure, lv_pct(40));
    lv_obj_set_x(ui_Pressure, lv_pct(-23));
    lv_obj_set_y(ui_Pressure, lv_pct(20));
    lv_obj_set_align(ui_Pressure, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Pressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_Pressure, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pressure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureLabel = lv_label_create(ui_Pressure);
    lv_obj_set_width(ui_PressureLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_PressureLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_PressureLabel, 10);
    lv_obj_set_y(ui_PressureLabel, 5);
    lv_label_set_text(ui_PressureLabel, "Pressure");
    lv_obj_set_style_text_font(ui_PressureLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureImage = lv_image_create(ui_Pressure);
    lv_image_set_src(ui_PressureImage, &ui_img_pressure_png);
    lv_obj_set_width(ui_PressureImage, 32);  // Keep container size larger
    lv_obj_set_height(ui_PressureImage, 32);  // Keep container size larger
    lv_image_set_scale(ui_PressureImage, (int)(0.55f * LV_SCALE_NONE));  // Scale image content to 55%
    lv_obj_set_x(ui_PressureImage, 35);
    lv_obj_set_y(ui_PressureImage, 31);
    lv_obj_set_align(ui_PressureImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PressureImage, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_PressureImage, LV_OBJ_FLAG_SCROLLABLE);

    ui_PressureText = lv_label_create(ui_Pressure);
    lv_obj_set_width(ui_PressureText, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_PressureText, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_PressureText, -15);
    lv_obj_set_y(ui_PressureText, -5);
    lv_obj_set_align(ui_PressureText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureText, "1013.2");
    lv_obj_set_style_text_font(ui_PressureText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureUnit = lv_label_create(ui_Pressure);
    lv_obj_set_width(ui_PressureUnit, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_PressureUnit, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_PressureUnit, 30);
    lv_obj_set_y(ui_PressureUnit, -11);
    lv_obj_set_align(ui_PressureUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureUnit, "hPa");
    lv_obj_set_style_text_font(ui_PressureUnit, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureTrend = lv_label_create(ui_Pressure);
    lv_obj_set_width(ui_PressureTrend, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_PressureTrend, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_PressureTrend, -5);
    lv_obj_set_y(ui_PressureTrend, 13);
    lv_obj_set_align(ui_PressureTrend, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureTrend, "Maybe Sunny");
    lv_obj_set_style_text_font(ui_PressureTrend, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQuality = lv_obj_create(ui_TemperatureScreen);
    lv_obj_remove_style_all(ui_AirQuality);
    lv_obj_set_width(ui_AirQuality, lv_pct(40));
    lv_obj_set_height(ui_AirQuality, lv_pct(40));
    lv_obj_set_x(ui_AirQuality, lv_pct(23));
    lv_obj_set_y(ui_AirQuality, lv_pct(20));
    lv_obj_set_align(ui_AirQuality, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AirQuality, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(ui_AirQuality, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AirQuality, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AirQuality, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQualityLabel = lv_label_create(ui_AirQuality);
    lv_obj_set_width(ui_AirQualityLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_AirQualityLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_AirQualityLabel, 10);
    lv_obj_set_y(ui_AirQualityLabel, 5);
    lv_label_set_text(ui_AirQualityLabel, "Air Quality");
    lv_obj_set_style_text_font(ui_AirQualityLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Leaf = lv_image_create(ui_AirQuality);
    lv_image_set_src(ui_Leaf, &ui_img_leaf_png);
    lv_obj_set_width(ui_Leaf, 32);  // Keep container size larger
    lv_obj_set_height(ui_Leaf, 32);  // Keep container size larger
    lv_image_set_scale(ui_Leaf, (int)(0.55f * LV_SCALE_NONE));  // Scale image content to 55%
    lv_obj_set_x(ui_Leaf, 40);
    lv_obj_set_y(ui_Leaf, 30);
    lv_obj_set_align(ui_Leaf, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Leaf, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Leaf, LV_OBJ_FLAG_SCROLLABLE);

    ui_AirQualityLevel = lv_label_create(ui_AirQuality);
    lv_obj_set_width(ui_AirQualityLevel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_AirQualityLevel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_AirQualityLevel, 0);
    lv_obj_set_y(ui_AirQualityLevel, -5);
    lv_obj_set_align(ui_AirQualityLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirQualityLevel, "Good");
    lv_obj_set_style_text_font(ui_AirQualityLevel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQualityCO2 = lv_label_create(ui_AirQuality);
    lv_obj_set_width(ui_AirQualityCO2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_AirQualityCO2, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_AirQualityCO2, -35);
    lv_obj_set_y(ui_AirQualityCO2, 16);
    lv_obj_set_align(ui_AirQualityCO2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirQualityCO2, "CO2:");
    lv_obj_set_style_text_font(ui_AirQualityCO2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQualityNumber = lv_label_create(ui_AirQuality);
    lv_obj_set_width(ui_AirQualityNumber, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_AirQualityNumber, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_AirQualityNumber, -8);
    lv_obj_set_y(ui_AirQualityNumber, 16);
    lv_obj_set_align(ui_AirQualityNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirQualityNumber, "450");
    lv_obj_set_style_text_font(ui_AirQualityNumber, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQualitySignal = lv_label_create(ui_AirQuality);
    lv_obj_set_width(ui_AirQualitySignal, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_AirQualitySignal, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_AirQualitySignal, 17);
    lv_obj_set_y(ui_AirQualitySignal, 16);
    lv_obj_set_align(ui_AirQualitySignal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirQualitySignal, "ppm");
    lv_obj_set_style_text_font(ui_AirQualitySignal, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AirQualitySignal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_TemperatureScreen_screen_destroy(void)
{
    if (ui_TemperatureScreen) {
        lv_obj_del(ui_TemperatureScreen);
    }

    ui_TemperatureScreen = NULL;
    ui_Temperature = NULL;
    ui_TemperatureLabel = NULL;
    ui_TemperatureNumber = NULL;
    ui_TemperatureSignal = NULL;
    ui_Thermometer = NULL;
    ui_Fire = NULL;
    ui_Humidity = NULL;
    ui_HumidityLabel = NULL;
    ui_Water = NULL;
    ui_HumidityNumber = NULL;
    ui_HumidityUnit = NULL;
    ui_HumidityEvaluation = NULL;
    ui_Pressure = NULL;
    ui_PressureLabel = NULL;
    ui_PressureImage = NULL;
    ui_PressureText = NULL;
    ui_PressureUnit = NULL;
    ui_PressureTrend = NULL;
    ui_AirQuality = NULL;
    ui_AirQualityLabel = NULL;
    ui_Leaf = NULL;
    ui_AirQualityCO2 = NULL;
    ui_AirQualityNumber = NULL;
    ui_AirQualityLevel = NULL;
    ui_AirQualitySignal = NULL;

}
