/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Temp

#ifndef UI_TEMPERATURETIPSCREEN_H
#define UI_TEMPERATURETIPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TemperatureTipScreen
extern void ui_TemperatureTipScreen_screen_init(void);
extern void ui_TemperatureTipScreen_screen_destroy(void);
extern lv_obj_t *ui_TemperatureTipScreen;
extern lv_obj_t *ui_TemperatureTipText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
