/*
 * SPDX-FileCopyrightText: 2023-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

/* Version */
#if !defined(BROOKESIA_SYSTEM_PHONE_VER_MAJOR)
#   define BROOKESIA_SYSTEM_PHONE_VER_MAJOR  (0)
#endif
#if !defined(BROOKESIA_SYSTEM_PHONE_VER_MINOR)
#   define BROOKESIA_SYSTEM_PHONE_VER_MINOR  (7)
#endif
#if !defined(BROOKESIA_SYSTEM_PHONE_VER_PATCH)
#   define BROOKESIA_SYSTEM_PHONE_VER_PATCH  (0)
#endif

/* Debug log */
#define BROOKESIA_SYSTEM_PHONE_LOG_TAG "SysPhone"

#if !defined(ESP_BROOKESIA_PHONE_ENABLE_DEBUG_LOG)
#    if defined(CONFIG_ESP_BROOKESIA_PHONE_ENABLE_DEBUG_LOG)
#        define ESP_BROOKESIA_PHONE_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_ENABLE_DEBUG_LOG
#    else
#        define ESP_BROOKESIA_PHONE_ENABLE_DEBUG_LOG  (0)
#    endif
#endif

#if ESP_BROOKESIA_PHONE_ENABLE_DEBUG_LOG
#   if !defined(ESP_BROOKESIA_PHONE_APP_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_APP_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_APP_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_APP_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_APP_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(ESP_BROOKESIA_PHONE_HONE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_HONE_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_HONE_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_HONE_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_HONE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(ESP_BROOKESIA_PHONE_MANAGER_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_MANAGER_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_MANAGER_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_MANAGER_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_MANAGER_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(ESP_BROOKESIA_PHONE_PHONE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_PHONE_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_PHONE_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_PHONE_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_PHONE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(ESP_BROOKESIA_PHONE_APP_LAUNCHER_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_APP_LAUNCHER_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_APP_LAUNCHER_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_APP_LAUNCHER_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_APP_LAUNCHER_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(ESP_BROOKESIA_PHONE_GESTURE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_GESTURE_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_GESTURE_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_GESTURE_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_GESTURE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(ESP_BROOKESIA_PHONE_NAVIGATION_BAR_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_NAVIGATION_BAR_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_NAVIGATION_BAR_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_NAVIGATION_BAR_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_NAVIGATION_BAR_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(ESP_BROOKESIA_PHONE_RECENTS_SCREEN_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_RECENTS_SCREEN_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_RECENTS_SCREEN_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_RECENTS_SCREEN_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_RECENTS_SCREEN_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(ESP_BROOKESIA_PHONE_STATUS_BAR_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_ESP_BROOKESIA_PHONE_STATUS_BAR_ENABLE_DEBUG_LOG)
#           define ESP_BROOKESIA_PHONE_STATUS_BAR_ENABLE_DEBUG_LOG  CONFIG_ESP_BROOKESIA_PHONE_STATUS_BAR_ENABLE_DEBUG_LOG
#       else
#           define ESP_BROOKESIA_PHONE_STATUS_BAR_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif
