/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Temp

#ifndef _TEMP_UI_H
#define _TEMP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_TemperatureScreen.h"
#include "screens/ui_TemperatureTipScreen.h"

///////////////////// VARIABLES ////////////////////

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_temp_png);    // assets/Temp.png
LV_IMG_DECLARE(ui_img_fire_png);    // assets/Fire.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_pressure_png);    // assets/Pressure.png
LV_IMG_DECLARE(ui_img_leaf_png);    // assets/Leaf.png

// UI INIT
void Temperature_ui_init(bool is_initialized);
void Temperature_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
