/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Compass

#ifndef UI_COMPASSCORRECTSCREEN_H
#define UI_COMPASSCORRECTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CompassCorrectScreen
extern void ui_CompassCorrectScreen_screen_init(void);
extern void ui_CompassCorrectScreen_screen_destroy(void);
extern lv_obj_t *ui_CompassCorrectScreen;
extern lv_obj_t *ui_CorrectImage;
extern lv_obj_t *ui_CorrectTips;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
