/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Compass

#include "../ui.h"
#include "../../compass_wrapper.hpp"
#include "core/lv_obj_style_gen.h"

lv_obj_t *ui_CompassTipScreen = NULL;
lv_obj_t *ui_CompassTipText = NULL;
// event functions

// build functions

void ui_CompassTipScreen_screen_init(void)
{
    ui_CompassTipScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CompassTipScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_CompassTipScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassTipScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompassTipText = lv_label_create(ui_CompassTipScreen);
    lv_obj_set_style_text_color(ui_CompassTipText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CompassTipText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_width(ui_CompassTipText, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_CompassTipText, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_CompassTipText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CompassTipText,
                      "BMI270 sub-board not detected.\nPower off and insert sub-board.\nDo NOT hot-plug.");
    lv_label_set_long_mode(ui_CompassTipText, LV_LABEL_LONG_WRAP);
    lv_obj_set_style_text_align(ui_CompassTipText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CompassTipText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_CompassTipScreen_screen_destroy(void)
{
    if (ui_CompassTipScreen) {
        lv_obj_del(ui_CompassTipScreen);
    }

    ui_CompassTipScreen = NULL;
    ui_CompassTipText = NULL;

}
