/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Compass

#include "../ui.h"

lv_obj_t *ui_CompassCorrectScreen = NULL;
lv_obj_t *ui_CorrectImage = NULL;
lv_obj_t *ui_CorrectTips = NULL;

/**
 * @brief Initialize the compass correction screen
 *
 * Creates and configures the UI elements for the compass calibration screen,
 * including the background, correction image, and instruction text.
 */
void ui_CompassCorrectScreen_screen_init(void)
{
    ui_CompassCorrectScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CompassCorrectScreen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_CompassCorrectScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CompassCorrectScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CorrectImage = lv_image_create(ui_CompassCorrectScreen);
    lv_image_set_src(ui_CorrectImage, &ui_img_correct_screen_png);
    lv_obj_set_width(ui_CorrectImage, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_CorrectImage, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_CorrectImage, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_CorrectImage, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_CorrectImage, LV_OBJ_FLAG_SCROLLABLE);

    ui_CorrectTips = lv_label_create(ui_CompassCorrectScreen);
    lv_obj_set_style_text_color(ui_CorrectTips, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CorrectTips, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CorrectTips, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_width(ui_CorrectTips, 220);
    lv_obj_set_height(ui_CorrectTips, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_CorrectTips, LV_ALIGN_TOP_MID);
    lv_obj_set_y(ui_CorrectTips, 20);
    lv_label_set_text(ui_CorrectTips, "Rotate device in figure-8\n(forward/backward more)");
}

/**
 * @brief Destroy the compass correction screen
 *
 * Releases all UI resources associated with the compass correction screen.
 * Child objects are automatically deleted when the parent screen is deleted.
 */
void ui_CompassCorrectScreen_screen_destroy(void)
{
    if (ui_CompassCorrectScreen) {
        lv_obj_del(ui_CompassCorrectScreen);
    }

    ui_CompassCorrectScreen = NULL;
    ui_CorrectImage = NULL;
    ui_CorrectTips = NULL;
}
