/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Compass

#ifndef UI_COMPASSTIPSCREEN_H
#define UI_COMPASSTIPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CompassTipScreen
extern void ui_CompassTipScreen_screen_init(void);
extern void ui_CompassTipScreen_screen_destroy(void);
extern lv_obj_t *ui_CompassTipScreen;
extern lv_obj_t *ui_CompassTipText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
