/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Compass

#ifndef UI_COMPASSSCREEN_H
#define UI_COMPASSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CompassScreen
extern void ui_CompassScreen_screen_init(void);
extern void ui_CompassScreen_screen_destroy(void);
extern void ui_event_CompassScreen(lv_event_t *e);
extern lv_obj_t *ui_CompassScreen;
extern lv_obj_t *ui_Pointer;
extern lv_obj_t *ui_ProgressBar;
extern lv_obj_t *ui_CalibrationTip;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
